import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links =[
  {href:'/', label:'Home'},
  {href:'/docs', label:'Docs'},
  {href:'/todos', label:'Todos'}
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 text-white py-4">
          <nav className="container mx-auto">
            <ul className="flex items-center">
              {links.map((link)=>(
                  <li className='ml-4'>
                    <Link href={link.href}>
                      {link.label}
                    </Link>
                  </li>
                ))}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
